/**
 * Single source of truth for the canonical site origin and shared brand data.
 * Every absolute URL in the app (canonical, OG, Twitter, JSON-LD, sitemap,
 * robots) is derived from `SITE_URL` so a stray localhost value can never ship.
 */

function normalizeOrigin(value: string | undefined): string {
  const fallback = "https://www.heilc.com";
  if (!value) return fallback;

  const trimmed = value.trim().replace(/\/+$/, "");
  if (!trimmed) return fallback;

  // Never let a development origin leak into production-facing metadata.
  if (/^https?:\/\/(localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])(:\d+)?$/i.test(trimmed)) {
    return process.env.NODE_ENV === "production" ? fallback : trimmed;
  }

  return /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
}

export const SITE_URL = normalizeOrigin(process.env.NEXT_PUBLIC_SITE_URL);

/** Build an absolute URL on the canonical origin. */
export function absoluteUrl(path = "/"): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

export const SITE_NAME = "HEILC";
export const SITE_TAGLINE = "Where Human Intelligence Meets the Future";

export const CONTACT_EMAIL = "hello@heilc.com";

/** Locality-level only — HEILC has no published street address. */
export const BUSINESS_LOCATION = {
  addressLocality: "Chennai",
  addressRegion: "Tamil Nadu",
  addressCountry: "IN",
  latitude: 13.0827,
  longitude: 80.2707,
  timezone: "Asia/Kolkata",
} as const;

export const SOCIAL_LINKS = {
  linkedin: "https://www.linkedin.com/company/heilc",
  instagram: "https://www.instagram.com/heilc",
  github: "https://github.com/heilc",
  twitter: "https://twitter.com/heilc",
} as const;

export const SAME_AS: string[] = [
  SOCIAL_LINKS.linkedin,
  SOCIAL_LINKS.instagram,
  SOCIAL_LINKS.github,
  SOCIAL_LINKS.twitter,
];

/** 1200x630 social card generated by app/opengraph-image.tsx. */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "HEILC — AI & Digital Transformation Agency",
} as const;
